development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: classical_development
  pool: 5
  username: root
  password: adminadmin
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: classical_test
  pool: 5
  username: root
  password: adminadmin
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: classical_production
  pool: 5
  username: root
  password: adminadmin
  host: localhost

